.TH git-submodule "November 2024" "Version 1.0" "User Commands"
.SH NAME
git submodule \- Managing git submodules.
.SH SYNOPSIS
\fBgit submodule add\fR [<options>]
.br
\fBgit submodule init\fR [<options>]
.br
\fBgit submodule update\fR [--remote] [<options>]
.br
tbd
.SH WORKFLOW
.TP
tbd
.SH FILE .gitmodules
.TP
You can specify submodule parameters in the .gitmodules file. 
.TP
branch = <branchname> 
Allows to specify the branch. Then, run `git submodule update --remote` to update the registry.