.TH git-remote "May 2024" "Version 1.0" "User Commands"
.SH NAME
git remote \- Managing git remotes.
.SH SYNOPSIS
\fBgit remote\fR [<options>]
.br
\fBgit remote add\fR  <name> <url>
.SH OPTIONS
.TP
-v
List the configured remotes.
.TP
-vv
tbd
.SH SEE ALSO
.TP
\fBgit clone\fR 
Copy and track a remote repository directly.
.TP
\fBgit fetch\fR --prune
Delete references to a deleted remote branch.